### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by acreegan** [hsorby/opencmiss2cmlibs#2]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\acre018\\github\\lung_batch_fit\\venv\\lib\\site-packages\\libocm2cml\\Grammar3.9.0.final.0.pickle'

**Comment by hsorby** [comment]
Whoops, my apologies.  I'm looking at fixing this now.

**Comment by hsorby** [comment]
I have made a fix and uploaded a new distribution to [Pypi](https://pypi.org/project/opencmiss2cmlibs/).  If you could give this one a try and see if the error has been resolved.

**Comment by acreegan** [comment]
Runs fine now thanks. Unfortunately the lung_batch_fit is still not working, I guess due to api changes since it was written. I think Mahyar is working on this though

**Comment by hsorby** [comment]
Sounds good, I'll close this issue then.
